### ISSUE TITLE
clique is not ready

### ISSUE THREAD

**Issue by autumnot** [alephium/mining-pool#25]
<img width="726" alt="b" src="https://user-images.githubusercontent.com/93163630/150717076-af992b3d-cf0b-4176-8794-808c078c9e78.png">
Node was run in a Windows environment, and the pool was Ubuntu. Is there a solution?

**Comment by Lbqds** [comment]
It should work if you can connect to the full node, you can check by running 
```
curl -X 'GET' \
  'http://host:12973/infos/self-clique' \
  -H 'accept: application/json' 
```
replace the `host` with your full node IP.

**Comment by autumnot** [comment]
<img width="734" alt="c" src="https://user-images.githubusercontent.com/93163630/150718846-4017af11-0ed9-4990-9666-9de72a5ec6ef.png">
Node sync is sure 
I just entered 4 wallet addresses in config.json and entered the api key.
I think there is some other problem

**Comment by Lbqds** [comment]
Can you try setting `alephium.api.api-key` in your full node user.conf? and don't forget to update `daemon.apiKey` in the pool config.

**Comment by autumnot** [comment]
As you said, the node connection was completed, but

2022-01-24T04:47:16.977Z | error | Load public key, unlock wallet failed, error: Invalid mnemonic passphrase

I get the following error: I'm sure I typed the correct mnemonic . Is there any other input method?

I typed in "mnemonicPassphrase": word1 word2 word 3 word4 word5 ... etc

**Comment by autumnot** [comment]
> Can you try setting `alephium.api.api-key` in your full node user.conf? and don't forget to update `daemon.apiKey` in the pool config.

I use a proxy and it works. Thank you
