### ISSUE TITLE
 | info | Clique is not read

### ISSUE THREAD

**Issue by italodl** [alephium/mining-pool#27]
Hi,
after start the pool  i have the error:

2022-01-26T10:46:25.802Z | info | Clique is not ready.

in the config.json a don't have  the api key

        "apiKey": "xxx",             // alephium full node api key

the problem is the key missing? in this case where do I get it from?

**Comment by Lbqds** [comment]
`apiKey` is mandatory in previous full node, you can set `alephium.api.api-key="your-api-key"` in full node user.conf, where `your-api-key` length is larger than 32, I' ll make the pool `apiKey` optional later.
