### ISSUE TITLE
Load public key, unlock wallet failed, error: Invalid mnemonic passphrase

### ISSUE THREAD

**Issue by rhys19** [alephium/mining-pool#36]
Hello, the error is what the title says basically.
I setup alephium full node and mining pool and setup the config.json created a wallet, and a miner wallet and I put the passphrase in there but it keeps saying Invalid passphrase even though I put it in the config.json, is there something else I'm supposed to do?

it says it connects to my full node but it says that error `| error | Load public key, unlock wallet failed, error: Invalid mnemonic passphrase`

Full log:
```root@localhost:~/mining-pool# npm run start

> alephium-mining-pool@0.1.1 start
> node ./init.js

2022-02-07T15:41:49.604Z | info | Connected to alephium full node
2022-02-07T15:41:49.725Z | error | Load public key, unlock wallet failed, error: Invalid mnemonic passphrase
root@localhost:~/mining-pool# ```

**Comment by altinsoft** [comment]
Leave the mnemonic passphrase blank. Wallet name and password is sufficient. It gives an error when you enter the mnemonic passphrase. We are waiting for a solution.

**Comment by rhys19** [comment]
> Leave the mnemonic passphrase blank. Wallet name and password is sufficient. It gives an error when you enter the mnemonic passphrase. We are waiting for a solution.

Now I get Unknown address

**Comment by rhys19** [comment]
Yeah I keep getting this
`2022-02-07T19:50:53.611Z | error | Invalid miner address: PRIVATE, error: null`

and it is the correct wallet, confirmed letter by letter number by number via the swagger ui using same api key, etc it even successfully unlocks them but the alephium mining-pool won't recognize it for some reason

**Comment by rhys19** [comment]
nvm I figured it out, had to be the same as the one in user.conf
