### ISSUE TITLE
Pool Fee

### ISSUE THREAD

**Issue by altinsoft** [alephium/mining-pool#39]
Pool fee is not calculated. How should we calculate this?

**Comment by Lbqds** [comment]
https://github.com/alephium/mining-pool/blob/83af4248474149c78c2eeefedba51df9dd483590/config.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46

Defaults to 0.5% of coinbase rewards, the pool fee is `coinbaseReward * 0.005 - payoutTxsFee`.

**Comment by altinsoft** [comment]
> 

I understand, but it doesn't cut 0.5% when sending payments. It sends all the resulting rewards. Pool wallet account becomes zero!

**Comment by altinsoft** [comment]
> https://github.com/alephium/mining-pool/blob/83af4248474149c78c2eeefedba51df9dd483590/config.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46
> 
> Defaults to 0.5% of coinbase rewards, the pool fee is `coinbaseReward * 0.005 - payoutTxsFee`.

I understand, but it doesn't cut 0.5% when sending payments. It sends all the resulting rewards. Pool wallet account becomes zero!

**Comment by Lbqds** [comment]
> > https://github.com/alephium/mining-pool/blob/83af4248474149c78c2eeefedba51df9dd483590/config.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46
> > 
> > Defaults to 0.5% of coinbase rewards, the pool fee is `coinbaseReward * 0.005 - payoutTxsFee`.
> 
> I understand, but it doesn't cut 0.5% when sending payments. It sends all the resulting rewards. Pool wallet account becomes zero!

It cut 0.5% when reward at [here](https://github.com/alephium/mining-pool/blob/83af4248474149c78c2eeefedba51df9dd483590/lib/shareProcessor.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L226), if you send more transactions, 0.5% may not be enough, you can modify the withholdPercent in the config.

**Comment by altinsoft** [comment]
> 



> > > https://github.com/alephium/mining-pool/blob/83af4248474149c78c2eeefedba51df9dd483590/config.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L46
> > > 
> > > Defaults to 0.5% of coinbase rewards, the pool fee is `coinbaseReward * 0.005 - payoutTxsFee`.
> > 
> > 
> > I understand, but it doesn't cut 0.5% when sending payments. It sends all the resulting rewards. Pool wallet account becomes zero!
> 
> It cut 0.5% when reward at [here](https://github.com/alephium/mining-pool/blob/83af4248474149c78c2eeefedba51df9dd483590/lib/shareProcessor.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L226), if you send more transactions, 0.5% may not be enough, you can modify the withholdPercent in the config.

You are wrong. It doesn't cut. Please check the codes.
