### ISSUE TITLE
Lots of data in the 'mining notify'

### ISSUE THREAD

**Issue by rlinxy** [alephium/mining-pool#62]
Hi, we would like to list Alph in our pool. We have built our own pool, but the pool is sending a lot of data in the mining notify field, and consuming very large bandwidth.

So I have just tried this nodejs pool, but got the same result.

Any idea what's wrong is it? Is there some config for the node we should modify?

Thanks

**Comment by rlinxy** [comment]
Below are the tcp packets we captured between rig and this node pool:

{"id":3,"method":"mining.authorize","params":["1JAGbyn1qUZ8EeAHbQvad8Pk6u5qRRJ6BPjdfj5vLEm9u.RAYGAMER"]}

{"id":null,"method":"mining.set_difficulty","params":[1]}

{"id":3,"result":true}

{"method":"mining.set_extranonce","params":["f84d"],"id":null}

{"id":9,"method":"alph_submitHashrate","jsonrpc":"2.0","worker":"test","workerName":"test","params":["0","0x24908ad60a095c0611a4973ff6c231c4cdf8978e69d31c4acd5502d2120e0089"]}

626fd171f39c45b3b50000018d1183fcbe1b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b93","fromGroup":0,"toGroup":2,"headerBlob":"00070000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac650000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa0000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0f0000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c03170000000000002eb10c460a67dfd23a35a4a8b481103841e96df0d4b49f1407dc10000000000023e14e3897a7d2b1de6080f2e6a27bf41edbad9b475e1a6870d02000000000000775bf8c5c06178c1aeb8cc0b7fe7afaeb84bd9c7f30df15e9e8365da896607221e467ef86072393aec00e10fa561fc414e9a0c515f13fdc443c4a34981f86c49d9bd125ae58e08b29a62434466f980fe52b0cec6c30441520aa80000018d1183fcc21b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b94","fromGroup":0,"toGroup":3,"headerBlob":"00070000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac650000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa0000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0f0000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c03170000000000002eb10c460a67dfd23a35a4a8b481103841e96df0d4b49f1407dc10000000000023e14e3897a7d2b1de6080f2e6a27bf41edbad9b475e1a6870d02000000000000775bf8c5c06178c1aeb8cc0b7fe7afaeb84bd9c7f30df15e9e8365da896607221e467ef86072

0000000002052cd26288994ec73e87174d7671c84fb2ff8c6c7ed962a6013714de46dd05d1ca117198d40071c3a76176af1acad23605cd1cb740d745e2922349aa42b5bdb16bbab1cf0831ad118022ddacb6f9917321bae3903837b052a4440000018d1183fcde1b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b97","fromGroup":1,"toGroup":2,"headerBlob":"00070000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c031700000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa0000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0f0000000000014c5bb95e6c2dda3e2823e84522cab2c9ea93e4e632a9ce77e8b40000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac65000000000001a274043e4e25097f5350b582e1e7b1836fe4bac976af395267b6000000000002052cd26288994ec73e87174d7671c84fb2ff8c6c7ed962a6013714de46dd05d1ca117198d40071c3a76176af1acad23605cd1cb740d745e29223e244b4d5befcfba52fc1cb941912b8ce6e6394f15ef7c3497387b74a109cdc690000018d1183fcdf1b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b98","fromGroup":1,"toGroup":3,"headerBlob":"00070000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c031700000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa0000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0f0000000000014c5bb95e6c2dda3e2823e84522cab2c9ea93e4e632a9ce77e8b40000000000013bade7a93847d1f2921b71e65b551cfb

88b685417b6a6d346b70be8391b3e3158fc58a9c880000000000027f91e0b4914677eb7c06b5ec86f3635604e6310cd3508ce29f490000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa0000000000007816d1e7ab77286cbe546adebdd26885edddf55e2140200695dbdec4de82782da7d4188036854ee58e333feb901926952d8d86a6199d7a492b0f39358384fb02479469c8ca1d3c08117760ed1b2a45a198b1a3a61e03aaba34b20000018d1183fcf11b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b9b","fromGroup":2,"toGroup":2,"headerBlob":"00070000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c031700000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac650000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0f000000000002efcbfdc91c88b685417b6a6d346b70be8391b3e3158fc58a9c880000000000027f91e0b4914677eb7c06b5ec86f3635604e6310cd3508ce29f490000000000028c7529079988c8abb1926b1b7935c419017b1a4aaad785e7ba8a0000000000007816d1e7ab77286cbe546adebdd26885edddf55e2140200695db233052dca83ab5f249cca9edd84e8cf20999f7a2f9d231a5ca3a9a156f5256772ab665df06f82f19f6e242c591f9a38e941063fb003c9822c093bcbf4d22a60e0000018d1183fcf11b031e66","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b9c","fromGroup":2,"toGroup":3,"headerBlob":"00070000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c031700000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac65

b40f2c49a2095ba7c031700000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac650000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa000000000002cbc645db6a6c1c6b1a1f3df71c3ae70efd479eece8bcadb1cacc0000000000017ad93a88c252ac4a266fc4833529c8120caeb60ba465c92642bd000000000002a9a260442ac1e57058894a8d93500450289631b439b2ce494bce0000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0fd85edc03316d11bd0c53acff3844aa33abfa81ef4a2ec01337a1d78d00d2d5c26bb5cd7bc9b999a9d934c46a22589be31ed25010f197b687a8ec22431413d7e20000018d1183fd071b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"b9f","fromGroup":3,"toGroup":2,"headerBlob":"00070000000000016ca6cef421c3bc8599b3c9a6e7459bb40f2c49a2095ba7c031700000000000013bade7a93847d1f2921b71e65b551cfb95e2642d5a15b576ac650000000000002c88c739fce5d8a874e64d102b4f706dfdad0ddbd3b3816ea8fa000000000002cbc645db6a6c1c6b1a1f3df71c3ae70efd479eece8bcadb1cacc0000000000017ad93a88c252ac4a266fc4833529c8120caeb60ba465c92642bd000000000002a9a260442ac1e57058894a8d93500450289631b439b2ce494bce0000000000026e7eded7cad96346cae716309e669479227c7b5c9c1458a5fc0fd85edc03316d11bd0c53acff3844aa33abfa81ef4a2ec01337a1d78d00d2d5c22cafdc8982abf54f356ba0f4b4e19b8adbc32a47e25795c2c004e4492cb167f10000018d1183fd071b03244b","txsBlob":"","targetBlob":"03ffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},{"jobId":"ba0",

**Comment by rlinxy** [comment]
Below is from Herominers

{"id":3,"method":"mining.authorize","params":["1JAGbyn1qXXXXXXXXXXXXXJ6BPjdfj5vLEm9u.test"]}

{"id":3,"error":null,"result":true}
{"id":null,"method":"mining.set_extranonce","params":["577f"]}

{"id":null,"method":"mining.notify","params":[{"jobId":"36053","fromGroup":0,"toGroup":3,"txsBlob":"","headerBlob":"00070000000000021daf5b3db4e05cecacb0859f7234e64e6aaf35e2de9b3b1a24a5000000000004312c373d539f9c74e461a6dadd4096612c7d816a57b439099d7a000000000000526928463d572597cc0f3b3c036f287de285910a0b9902dff83f0000000000047c735972e86e86cdb1f8bf697ef052a2507f740a2fd98be4ed200000000000006de99e03bf9c3a2295035259eb6ed1700000204a9093556ca6e1000000000000cfc025e8852b1f3d5bee2205f76f72d98e6c0ddd81becda7e3c20000000000036d3ac2a0a32920e79ff0855df3c8db8f3cec817084c435dff71327cd1ed50c27dc46fe94039cb1de443294fcaa444a6725d52bf70eebe1b8e084a298011e4eff539ecaba611c786fa598a3243ee7cc9d75bd1f40d4b323ea447c0000018ce824f1b91b04aa83","targetBlob":"000000016e80fe033c8c643dd915716d418dd5d7fa3e60faad9c9cc5341318f8"}]}

{"id":9,"method":"alph_submitHashrate","jsonrpc":"2.0","worker":"1JAGbyn1qUZ8EeAHbQvad8Pk6u5qRRJ6BPjdfj5vLEm9u","workerName":"RAYGAMER","params":["0","0x608373dffe00ef206ce5119e5791841a5543b4e341eb9bf10522eb5f3e2c1299"]}

{"id":9,"error":null,"result":true}

{"id":null,"method":"mining.notify","params":[{"jobId":"3606d","fromGroup":3,"toGroup":1,"txsBlob":"","headerBlob":"00070000000000047c735972e86e86cdb1f8bf697ef052a2507f740a2fd98be4ed200000000000021daf5b3db4e05cecacb0859f7234e64e6aaf35e2de9b3b1a24a5000000000004312c373d539f9c74e461a6dadd4096612c7d816a57b439099d7a000000000001914de69a3c076f0822096b75eb5ba2caf02c690d12fd161f66cc000000000003ec8fbb2d1234dbfffef5509fa540f8dc1d1b8c8a7541099f869d000000000000805bb9fe5ea279c6dfac26553057a4b19b67de045c828d02161e000000000000a3bc02e26dcde6f66437f5cbcbaf5170f83a335b6bde0d7988ffa3e7a02718c0c61729e79b52b74a336d839c691e55e44d9ed5a14ee90b266e3f9e4052f96ad1b5e6c8ec1fcb029fdd8bd41095de60648331cd8beec91eeb4a600000018ce8250d501b04aa83","targetBlob":"000000016e80fe033c8c643dd915716d418dd5d7fa3e60faad9c9cc5341318f8"}]}


{"id":null,"method":"mining.notify","params":[{"jobId":"36076","fromGroup":1,"toGroup":2,"txsBlob":"","headerBlob":"00070000000000047c735972e86e86cdb1f8bf697ef052a2507f740a2fd98be4ed20000000000004312c373d539f9c74e461a6dadd4096612c7d816a57b439099d7a000000000000a3bc02e26dcde6f66437f5cbcbaf5170f83a335b6bde0d7988ff000000000003a8585602c3650196e14d019be4394bb702820a51162672d0b1f40000000000021daf5b3db4e05cecacb0859f7234e64e6aaf35e2de9b3b1a24a50000000000030648f9af16d58e4933b1b2e903208f1faaef2e4214bb1e56c866000000000000445a6a99180ab68d9a467fd181403009e3e0a69106f8b42c4ec7c4285434c4be4fe1e9f85f8b798606d85727dd3db7f1aa48407111887e92aa348356eedddf238b7dd3308f8b74f968cea69de66019d849024973db662b3964120000018ce8252c7c1b04aa83","targetBlob":"000000016e80fe033c8c643dd915716d418dd5d7fa3e60faad9c9cc5341318f8"}]}

{"id":null,"method":"mining.notify","params":[{"jobId":"36087","fromGroup":1,"toGroup":3,"txsBlob":"","headerBlob":"00070000000000047c735972e86e86cdb1f8bf697ef052a2507f740a2fd98be4ed20000000000004312c373d539f9c74e461a6dadd4096612c7d816a57b439099d7a000000000000a3bc02e26dcde6f66437f5cbcbaf5170f83a335b6bde0d7988ff000000000003a8585602c3650196e14d019be4394bb702820a51162672d0b1f40000000000021daf5b3db4e05cecacb0859f7234e64e6aaf35e2de9b3b1a24a50000000000030648f9af16d58e4933b1b2e903208f1faaef2e4214bb1e56c86600000000000434f50ac9ff7c82b839f71ce3c8d38ad2cd9d95e90346b77e2ef7c4285434c4be4fe1e9f85f8b798606d85727dd3db7f1aa48407111887e92aa34dfeaa6c1318c54aea2441826ad15378e786505b2e379a8447ebb2ae5e302c5900000018ce8252e041b04aa83","targetBlob":"000000016e80fe033c8c643dd915716d418dd5d7fa3e60faad9c9cc5341318f8"}]}

{"id":null,"method":"mining.notify","params":[{"jobId":"3609b","fromGroup":2,"toGroup":3,"txsBlob":"","headerBlob":"00070000000000047c735972e86e86cdb1f8bf697ef052a2507f740a2fd98be4ed200000000000031f1ec0b60df30d2fd5114a23b3172fcf89c2a72897cf41254855000000000000a3bc02e26dcde6f66437f5cbcbaf5170f83a335b6bde0d7988ff0000000000017c6410c5f52130f097976366e7fe669a821906334403d2091f580000000000005284bc89ab8b8d3f5e72518e3fcbb53b8a3ce2ec123e94e938c9000000000004312c373d539f9c74e461a6dadd4096612c7d816a57b439099d7a000000000001eedea11ab3c7118716eff61b882d829d9c4ae7f3b2f4a10b661b33ad770e589c86362d06c49516a508383ec40190532b420a14750f5bcf9a1ee1e4c34e964e359458517a81df0caa8de25c54005777cc1836e6e5c921b89a6d1c0000018ce82530541b04aa83","targetBlob":"000000016e80fe033c8c643dd915716d418dd5d7fa3e60faad9c9cc5341318f8"}]}


{"id":null,"method":"mining.notify","params":[{"jobId":"360ae","fromGroup":3,"toGroup":2,"txsBlob":"","headerBlob":"00070000000000047c735972e86e86cdb1f8bf697ef052a2507f740a2fd98be4ed200000000000031f1ec0b60df30d2fd5114a23b3172fcf89c2a72897cf41254855000000000004312c373d539f9c74e461a6dadd4096612c7d816a57b439099d7a000000000001914de69a3c076f0822096b75eb5ba2caf02c690d12fd161f66cc000000000003ec8fbb2d1234dbfffef5509fa540f8dc1d1b8c8a7541099f869d000000000000805bb9fe5ea279c6dfac26553057a4b19b67de045c828d02161e000000000000a3bc02e26dcde6f66437f5cbcbaf5170f83a335b6bde0d7988ffa3e7a02718c0c61729e79b52b74a336d839c691e55e44d9ed5a14ee90b266e3f51b51a55310c0a3b53a70abb97332e00f18a125513e89d6d730d088856191ee90000018ce82532351b04aa83","targetBlob":"000000016e80fe033c8c643dd915716d418dd5d7fa3e60faad9c9cc5341318f8"}]}

**Comment by rlinxy** [comment]
The data is like 20 times more than what between Herominer and same rig.
Please advice, thanks.

**Comment by polarker** [comment]
@rlinxy I think we know the issue. I will elaborate on the details when I am more available.

**Comment by rlinxy** [comment]
> @rlinxy I think we know the issue. I will elaborate on the details when I am more available.

Thanks, but we are trying to build our own pool, not just use this nodejs one, so would you provide some advice on this?

**Comment by polarker** [comment]
> > @rlinxy I think we know the issue. I will elaborate on the details when I am more available.
> 
> Thanks, but we are trying to build our own pool, not just use this nodejs one, so would you provide some advice on this?

I am a bit busy for now, so I will explain quickly. Later we will document more of the details.

We have 16 chains, and pools need to distribute the miners' hashrate evenly on these chains. The reference implementation sends 16 tasks to miners, but you could also find a way to send 1 task to each miner and make sure that the 16 tasks get a similar amount of hashrate.

**Comment by rlinxy** [comment]
Got it, thanks
